// Example inputs for the PHP unserialize tool. The Laravel payloads are real
// failed_jobs rows from a scratch Laravel 13.34 app on PHP 8.4 (fake data).

export const EXAMPLE_SERIALIZED =
  'O:5:"Child":6:{s:12:"\u0000Base\u0000secret";s:11:"base-secret";s:8:"\u0000*\u0000level";i:1;s:4:"name";s:4:"base";s:13:"\u0000Child\u0000secret";s:12:"child-secret";s:7:"\u0000*\u0000tags";a:2:{i:0;s:1:"a";i:1;s:1:"b";}s:2:"id";i:7;}';
export const EXAMPLE_MULTIBYTE =
  'a:4:{s:4:"name";s:19:"Café ☕ 日本語";s:5:"emoji";s:8:"👍🏽";s:2:"ar";s:10:"مرحبا";s:5:"empty";s:0:"";}';
export const EXAMPLE_REFS =
  'a:3:{i:0;O:8:"stdClass":1:{s:1:"n";i:1;}i:1;r:2;s:1:"n";r:2;}';
export const EXAMPLE_JOB =
  '{\n  "uuid": "ea5ea40b-13f1-4829-a0fa-13d2ac07ac7c",\n  "displayName": "App\\\\Jobs\\\\SendInvoiceEmail",\n  "job": "Illuminate\\\\Queue\\\\CallQueuedHandler@call",\n  "maxTries": 3,\n  "maxExceptions": null,\n  "failOnTimeout": false,\n  "countCrashesAsExceptions": false,\n  "backoff": null,\n  "timeout": 120,\n  "retryUntil": null,\n  "deleteWhenMissingModels": false,\n  "data": {\n    "commandName": "App\\\\Jobs\\\\SendInvoiceEmail",\n    "command": "O:25:\\"App\\\\Jobs\\\\SendInvoiceEmail\\":5:{s:31:\\"\\u0000App\\\\Jobs\\\\SendInvoiceEmail\\u0000meta\\";a:4:{s:4:\\"note\\";s:19:\\"Café ☕ 日本語\\";s:6:\\"amount\\";d:19.99;s:4:\\"paid\\";b:0;s:3:\\"ref\\";N;}s:4:\\"user\\";O:45:\\"Illuminate\\\\Contracts\\\\Database\\\\ModelIdentifier\\":5:{s:5:\\"class\\";s:15:\\"App\\\\Models\\\\User\\";s:2:\\"id\\";i:1;s:9:\\"relations\\";a:0:{}s:10:\\"connection\\";s:6:\\"sqlite\\";s:15:\\"collectionClass\\";N;}s:5:\\"lines\\";a:2:{i:0;a:3:{s:3:\\"sku\\";s:9:\\"TSHIRT-01\\";s:3:\\"qty\\";i:2;s:5:\\"price\\";d:15.5;}i:1;a:3:{s:3:\\"sku\\";s:9:\\"MUG-ÉTÉ\\";s:3:\\"qty\\";i:1;s:5:\\"price\\";d:9;}}s:6:\\"status\\";E:23:\\"App\\\\Enums\\\\Status:Active\\";s:5:\\"queue\\";s:6:\\"emails\\";}",\n    "batchId": null\n  },\n  "createdAt": 1791187575,\n  "delay": null\n}';
export const EXAMPLE_ENCRYPTED =
  '{\n  "uuid": "65f8e2a0-1c1e-4170-a17a-53186fdd1581",\n  "displayName": "App\\\\Jobs\\\\EncryptedJob",\n  "job": "Illuminate\\\\Queue\\\\CallQueuedHandler@call",\n  "maxTries": null,\n  "maxExceptions": null,\n  "failOnTimeout": false,\n  "countCrashesAsExceptions": false,\n  "backoff": null,\n  "timeout": null,\n  "retryUntil": null,\n  "deleteWhenMissingModels": false,\n  "data": {\n    "commandName": "App\\\\Jobs\\\\EncryptedJob",\n    "command": "eyJpdiI6Ii9BQWU0bUdZS2hwZEp6R21neFltZWc9PSIsInZhbHVlIjoiN1dORHVkWXlzR3R4ZTJHblQ5RDBaQXFsWTdlczdwTEo1TWRySGhxS0N0ZWE2QkREN296OTErN2ZTV3ZUWk83MXBsQTc2Rkg5c3p6bUFBVzVMNFUvTy9xeDB6R1pGeVZabXI1aG9ycURqSlk9IiwibWFjIjoiNzMzMmUzMmVlNTQ1MGY2ZTk5M2JmZGRiNTk2YmUyMmNhZWE4Y2U3NmMzOTY0NWYyNDEzYmNjNTNmNTRjODU2OSIsInRhZyI6IiJ9",\n    "batchId": null\n  },\n  "createdAt": 1791187575,\n  "delay": null\n}';
