import type { ToolEntry } from "./04a1-tools-meta";

export const TOOL_LIST_A: ToolEntry[] = [
  // ── AI & LLM ──
  {
    title: "LLM Cost Calculator",
    blurb:
      "Estimate API spend across Claude, GPT and Gemini, with real prompt-cache read and write prices. See the monthly bill before you ship.",
    href: "/tools/llm-cost-calculator/",
    seoTitle: "LLM API Cost Calculator: Claude, GPT, Gemini",
    updated: "2026-10-03",
    verifiedLabel: "October 3, 2026 (model and cache prices)",
    services: ["ai"],
    icon: "lucide:calculator",
    tone: "yellow",
    status: "live",
    group: "ai",
    tags: ["llm", "ai-engineering", "llm-inference"],
  },
  {
    title: "Token Counter",
    blurb:
      "Paste any text for an exact GPT token count, plus Claude and Gemini estimates, characters, words and per-call cost. All in your browser.",
    href: "/tools/token-counter/",
    seoTitle: "Token Counter: Count GPT and Claude Tokens",
    updated: "2026-10-03",
    verifiedLabel: "October 3, 2026 (model prices)",
    services: ["ai"],
    icon: "lucide:hash",
    tone: "cyan",
    status: "live",
    group: "ai",
    tags: ["llm", "rag", "ai-engineering"],
  },
  {
    title: "Context Window Checker",
    blurb:
      "Will the prompt fit? Paste it and see tokens used, headroom left, and what's still free for the answer across Claude, GPT and Gemini windows.",
    href: "/tools/context-window-checker/",
    seoTitle: "Context Window Checker: Will My Prompt Fit?",
    updated: "2026-10-03",
    verifiedLabel: "October 3, 2026 (named model windows)",
    services: ["ai"],
    icon: "lucide:ruler",
    tone: "purple",
    status: "live",
    group: "ai",
    tags: ["llm", "rag", "agentic-ai"],
  },
  {
    title: "RAG Chunk Splitter",
    blurb:
      "Split text into retrieval chunks — fixed, sentence, paragraph, or markdown-heading aware — and see every chunk's token count and overlap seam.",
    href: "/tools/rag-chunk-splitter/",
    seoTitle: "RAG Chunk Splitter: Test Chunk Size and Overlap",
    updated: "2026-10-03",
    services: ["ai"],
    icon: "lucide:scissors",
    tone: "pink",
    status: "live",
    group: "ai",
    tags: ["rag", "vector-search", "pgvector"],
  },
  {
    title: "pgvector Size Calculator",
    blurb:
      "Rows and dimensions in, table size, HNSW or IVFFlat index size, RAM and maintenance_work_mem out. vector, halfvec and bit, with the formulas shown.",
    href: "/tools/pgvector-calculator/",
    seoTitle: "pgvector Size Calculator: HNSW Index and RAM",
    updated: "2026-10-04",
    services: ["ai", "audit"],
    icon: "lucide:database",
    tone: "green",
    status: "live",
    group: "ai",
    tags: ["pgvector", "vector-search", "databases"],
  },
  {
    title: "Prompt Caching Calculator",
    blurb:
      "Compare the LLM bill with and without prompt caching. Prefix tokens, hit rate, write premium and read discount in, savings and break even hit rate out.",
    href: "/tools/prompt-caching-calculator/",
    seoTitle: "Prompt Caching Calculator: LLM Cost Savings",
    updated: "2026-10-04",
    verifiedLabel: "October 4, 2026 (preset prices)",
    services: ["ai"],
    icon: "lucide:piggy-bank",
    tone: "yellow",
    status: "live",
    group: "ai",
    tags: ["llm", "llm-inference", "ai-engineering"],
  },

  {
    title: "MCP Config Generator",
    blurb:
      "Build the MCP server config for Claude Desktop, Claude Code, Cursor or VS Code, stdio or remote HTTP. Paste a config to find what is wrong with it.",
    href: "/tools/mcp-config-generator/",
    seoTitle: "MCP Config Generator and Validator",
    updated: "2026-10-04",
    verifiedLabel: "October 4, 2026 (client formats)",
    services: ["ai", "mvp"],
    icon: "lucide:cable",
    tone: "purple",
    status: "live",
    group: "ai",
    tags: ["mcp", "claude", "ai"],
  },

  // ── Encoding & secrets ──
  {
    title: "JWT Decoder",
    blurb:
      "Paste a JWT and read its header and payload — claims, algorithm, and expiry decoded in your browser. Decode-only; nothing is sent anywhere.",
    href: "/tools/jwt-decoder/",
    seoTitle: "JWT Decoder Online: Decode Tokens, No Upload",
    updated: "2026-08-12",
    services: ["mvp", "ai"],
    icon: "lucide:key-round",
    tone: "purple",
    status: "live",
    group: "encoding",
    tags: ["security", "api-design"],
  },
  {
    title: "Laravel Encrypt / Decrypt",
    blurb:
      "Decrypt or encrypt Laravel Crypt payloads and cookies with your APP_KEY. AES-CBC with MAC check and AES-GCM, all in your browser.",
    href: "/tools/laravel-encrypt-decrypt/",
    seoTitle: "Laravel Decrypt and Encrypt Online, Client-Side",
    updated: "2026-10-04",
    services: ["mvp"],
    icon: "lucide:lock-keyhole",
    tone: "pink",
    status: "live",
    group: "encoding",
    tags: ["laravel", "security"],
  },
  {
    title: "Base64 Encoder / Decoder",
    blurb:
      "Encode and decode base64 without the UTF-8 bugs — emoji and accents round-trip correctly. base64url and file-to-data-URI included.",
    href: "/tools/base64-encoder/",
    seoTitle: "Base64 Encode and Decode Online, UTF-8 Safe",
    updated: "2026-08-12",
    services: ["mvp"],
    icon: "lucide:binary",
    tone: "cyan",
    status: "live",
    group: "encoding",
    tags: ["api-design"],
  },
  {
    title: "SHA Hash Generator",
    blurb:
      "SHA-1, SHA-256, SHA-384 and SHA-512 for text or a file, plus HMAC with your own key. Hex or base64, Web Crypto, in your browser. No MD5, on purpose.",
    href: "/tools/hash-generator/",
    seoTitle: "SHA-256 and HMAC Generator Online (SHA-1, SHA-512)",
    updated: "2026-10-03",
    services: ["mvp", "shopify"],
    icon: "lucide:shield-check",
    tone: "green",
    status: "live",
    group: "encoding",
    tags: ["security"],
  },
  {
    title: "Secret & API Key Generator",
    blurb:
      "Keys, hex secrets, passphrases and Laravel APP_KEY values from crypto.getRandomValues, never Math.random. Unbiased sampling, entropy readout, nothing logged.",
    href: "/tools/secret-generator/",
    seoTitle: "Secret Key Generator: API Keys, Laravel APP_KEY",
    updated: "2026-10-03",
    services: ["mvp"],
    icon: "lucide:key-square",
    tone: "pink",
    status: "live",
    group: "encoding",
    tags: ["security"],
  },
  {
    title: "UUID Generator",
    blurb:
      "Generate v4 or time-ordered v7 UUIDs in bulk, and paste any UUID to read its version and timestamp. Crypto-random, instant, offline.",
    href: "/tools/uuid-generator/",
    seoTitle: "UUID Generator: Bulk v4 and v7, Plus Inspector",
    updated: "2026-10-03",
    services: ["mvp"],
    icon: "lucide:fingerprint",
    tone: "green",
    status: "live",
    group: "encoding",
    tags: ["databases", "api-design"],
  },

  // ── Data & APIs ──
  {
    title: "URL Parser & Encoder",
    blurb:
      "Break a URL into every part, edit query params and watch it rebuild. Plus the four encode/decode functions people keep mixing up.",
    href: "/tools/url-parser/",
    seoTitle: "URL Parser and Encoder: Edit Query Strings",
    updated: "2026-10-03",
    services: ["mvp"],
    icon: "lucide:link",
    tone: "yellow",
    status: "live",
    group: "data",
    tags: ["api-design", "networking"],
  },
  {
    title: "JSON Formatter & Validator",
    blurb:
      "Format, minify, sort keys — and when it breaks, get the line, the column, and a caret under the exact character, not just “Unexpected token”.",
    href: "/tools/json-formatter/",
    seoTitle: "JSON Formatter and Validator: Exact Error Line",
    updated: "2026-08-12",
    services: ["mvp"],
    icon: "lucide:braces",
    tone: "cyan",
    status: "live",
    group: "data",
    tags: ["api-design"],
  },
  {
    title: "PHP Unserialize & Laravel Job Decoder",
    blurb:
      "Read PHP serialized data as a tree and JSON without running any code. Paste a failed_jobs payload to see the job, its queue and the models it was given.",
    href: "/tools/php-unserialize/",
    seoTitle: "PHP Unserialize Online and Laravel Job Decoder",
    updated: "2026-10-05",
    services: ["mvp"],
    icon: "lucide:package-open",
    tone: "pink",
    status: "live",
    group: "data",
    tags: ["laravel", "messaging", "redis"],
  },
];
